---
- name: Deploy Web App
  hosts: n4
  become: yes
  tasks:
   - name: install Git
     yum:
       name: git
       state: present

   - name: Host code
     git:
       repo: https://github.com/preyelg/ansible-work-6.git 
       dest: /var/www/html
...
